title: Dexforce 3D Camera
description: A low cost, full featured open source, industrial 3D camera.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
feedback_email: wudi@dexforce.com
github:
  sourcecode_url: https://github.com/open3dv/xema
  docs_url: https://github.com/Open3DV/xema/tree/master/docs
  forum_url: https://open3dv.org.cn
